SET SHELL_DIR=A:

SET AdminUser=Administrateur
SET AdminGroup=Administrateurs
SET CloudAdmin=CloudAdmin

SET ZABBIX_SRV=192.168.145.8

SET SQLSERVER_ACCOUNT=ADLERE\svcSQLServer
SET SQLSERVER_PASSWORD=r_2-5LhXISptGkaY
SET SQLSERVER_SERIAL=PMBDC-FXVM3-T777P-N4FY8-PKFF4
SET SQLSERVER_SYSADMINACCOUNTS="ADLERE\Administrateur" "Administrateur" "ADLERE\odepertat"

SET SQLCMDPASSWORD=