#!/bin/bash

export mScript=`basename "$0"`
export mIncDir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $mIncDir/../abin/mShellLib
source $mIncDir/../abin/mShellLib-GitLab

export ANSIBLE_ROLES_PATH=$ANSIBLE_ROLES_PATH:${mIncDir}/../roles
export ANSIBLE_ROLES_PATH=$ANSIBLE_ROLES_PATH:${mIncDir}/common-roles

# WHen developping 
export ANSIBLE_ROLES_PATH=$ANSIBLE_ROLES_PATH:..

# WHen running inside a container
export ANSIBLE_ROLES_PATH=$ANSIBLE_ROLES_PATH:/var/lib/cicd


ansible-playbook  -i $mIncDir/../vars/${CI_TENANT}/inventory.yml $1 $2 $3 $4 $5 $6 $7 $8 $9