#!/bin/bash

export mScript=`basename "$0"`
export mIncDir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $mIncDir/mShellLib

rm -rf $mIncDir/common-roles 
ansible-galaxy install -p $mIncDir/common-roles -r $mIncDir/../vars/${CI_TENANT}/requirements.yml 
