#!/bin/bash

export mScript=`basename "$0"`
export mIncDir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $mIncDir/mShellLib-Vault

mCheckBinExists ansible-vault

# In that case 
if [ $# != 1 ]; then
  mErrorMessageAndExit "You must provide only one secret name at once" 1023
fi
mVaultSecretName=$1

#Caching VAULT Content if not defined
if [ -z mVAULT_CONTENT ];
then 
  export mVAULT_CONTENT=`ansible-vault view ${VAULT_ENV_FILE} --vault-id=${VAULT_ENV_PASSFILE}`
fi

echo "$mVAULT_CONTENT" | grep "$mVaultSecretName" |  awk -F ": " '{ print $2}'
