#!/bin/bash
####################################################
## 
## These tools are the property of Adlere
## usage is restricted to the final customer only.
##
## Distribution for Consulting purposes is prohibited
## without authorization.
##
## © 2022 Adlere ALL RIGHTS RESERVED
##
####################################################
mScript=`basename "$0"`
mIncDir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
set -e
source $mIncDir/../abin/mShellLib

mDockerSetEnv


podman run --rm \
    -v /tmp:/tmp \
    -v /cache \
    -v /rpoc \
    -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
    -v .:/var/lib/cicd/workdir:Z \
    --security-opt label=disable \
    $REPO_DOCKER_BUILDAH_IMAGE \
    sh -c "cd /var/lib/cicd/workdir ; source ./$UUID ;  /var/lib/cicd/bin/buildah-build"

rm -f $UUID

