#!/bin/bash
####################################################
## 
## These tools are the property of Adlere
## usage is restricted to the final customer only.
##
## Distribution for Consulting purposes is prohibited
## without authorization.
##
## © 2022 Adlere ALL RIGHTS RESERVED
##
####################################################
export mScript=`basename "$0"`
export mIncDir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $mIncDir/mShellLib
source $mIncDir/mShellLib-Vault

mCheckBinExists ansible-vault

mDebugPrintEnvVault
mDebugPrintCISecrets

ansible-vault view ${VAULT_ENV_FILE} --vault-id=${VAULT_ENV_PASSFILE} | sort -u