#!/bin/bash
export mScript=`basename "$0"`
export mIncDir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $mIncDir/mShellLib
source $mIncDir/mShellLib-Vault

mCheckBinExists ansible-vault

ansible-vault create ${VAULT_ENV_FILE} --vault-id=${VAULT_ENV_PASSFILE} 